basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path("login/", views.login_page, name="login_page"),
    path("about/", views.about_page, name="about_page"),
    path("dash/", views.dashboard_page, name="dashboard_page"),
    path("map/", views.map_page, name="map_page"),
    path("settings/", views.settings_page, name="settings_page"),
    path("sign/", views.sign_page, name="sign_page"),
    path("", views.main_page, name = "main_page"),
    path("logout/", views.logout_page, name = "logout_page"),
    path("send/", views.send_trafic_data, name = "send_trafic_data"),
    path("route/", views.map_the_route, name = "map_the_route"),
    path("change/", views.change_user_data, name = "change_user_data"),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main_page, name="main_page"),
    path("basicapp/", include("basic_app.urls", namespace="basic_app")),
    
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime

class AppUsers(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    ID_Uzytkownika = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    login = models.CharField(max_length=200, unique=True, default="login")
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=200)
    avatar = models.IntegerField()

    def __str__(self):
        return self.email
    

class Zgloszenie(models.Model):
    ID_Zgloszenia = models.AutoField(primary_key=True)
    ID_Uzytkownika = models.ForeignKey(AppUsers,null=True, on_delete=models.CASCADE)
    x = models.FloatField()
    y = models.FloatField()
    typ_zgloszenia = models.IntegerField()
    czas_dodania = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.czas_dodania:
            self.czas_dodania = timezone.now()
        super().save(*args, **kwargs)

basic_app/forms.py
from typing import Any, Dict
from django import forms
from basic_app.models import AppUsers
from django.core import validators


class NewAccount(forms.Form):
    name = forms.CharField(max_length=40, required=True, label="Imie: ")
    last_name = forms.CharField(max_length=40, required=True, label="Nazwisko: ")
    login = forms.CharField(max_length=40, required=True, label="Login: ")
    email  = forms.EmailField(required=True,label="E-mail: ")
    password = forms.CharField(widget=forms.PasswordInput(), label="Hasło: ")
    submit_password = forms.CharField(widget=forms.PasswordInput(), label="Powtórz hasło: ")
    terms_of_use = forms.BooleanField(label = "Akceptuję warunki i zasady korzystania z aplikacji")
    rodo = forms.BooleanField(label = "Akceptuję politykę prywatności i RODO")


    def clean_submit_password(self):     
        passwordd = self.cleaned_data['password']
        submit_password = self.cleaned_data['submit_password']

        if passwordd != submit_password:
            raise forms.ValidationError("Wprowadzone hasła różnią się!!!")
        if len(passwordd)<6:
            raise forms.ValidationError("Hasło musi mieć minimum 6 znaków!!!")
        return passwordd
    
    def clean_login(self):
        given_login = self.cleaned_data['login']
        login_exists = AppUsers.objects.filter(login=given_login).exists()
        if(len(given_login)<6):
            raise forms.ValidationError("login musi mieć minimum 6 znaków")
        elif(login_exists):
                raise forms.ValidationError("Podany login jest już zajęty! Wprowadź inny login!")

        return given_login
    
    def clean_email(self):
        given_email = self.cleaned_data['email']
        email_exists = AppUsers.objects.filter(email=given_email).exists()
        if(email_exists):
                raise forms.ValidationError("Podany email jest już zajęty! Wprowadź inny email!")

        return given_email
    
    

class SearchCords(forms.Form):
    adress = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Szukaj','class' :'form-control', 'id':'search-input'}), label=any, required=False)

class LogIn(forms.Form):
    login = forms.CharField(max_length=40, required=True, label="Login: ")
    password = forms.CharField(widget=forms.PasswordInput(), label="Hasło: ")
     
    def clean(self):
        cleaned_data = super().clean()
        login = cleaned_data.get('login')
        password = cleaned_data.get('password')
        correct_login = False
        if login and password:
            try:
                AppUsers.objects.get(login=login)
                correct_login = True
            except AppUsers.DoesNotExist:
                self.add_error('login', "Nie ma użytkownika o podanym loginie")

            if correct_login:
                try:
                    user = AppUsers.objects.get(login=login, password=password)
                except AppUsers.DoesNotExist:
                    self.add_error('password', "Wpisano złe hasło")
        
        return cleaned_data

           
           
     

basic_app/views.py
from django.shortcuts import render
from basic_app import forms
from basic_app.models import AppUsers, Zgloszenie
from geopy.geocoders import Nominatim
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest
import json
from django.utils import timezone
import random
from django.core.validators import validate_email
from django.core.exceptions import ValidationError



# Create your views here.
def get_coordinates(city, street):
    geolocator = Nominatim(user_agent="my-app") # utwórz obiekt geolokalizatora
    location = geolocator.geocode(f"{street}, {city}") # pobierz współrzędne geograficzne
    try:
        return location.latitude, location.longitude
    except AttributeError:
        return False

def main_page(request):
    user = request.user
    if user.is_authenticated:
        app_user = AppUsers.objects.get(user=user)
        avatar = str(app_user.avatar)
        context = {
            'user': user,
            'avatar': avatar,
        }
    else:
        context = {
            'user': user,
        }
    return render(request, 'basic_app/main.html', context)

from django.contrib.auth import authenticate, login

from django.contrib.auth import authenticate, login

def login_page(request):
    if request.method == "POST":
        login_form = forms.LogIn(request.POST)
        if login_form.is_valid():
            # Sprawdź poprawność formularza i uzyskaj dostęp do danych
            login_value = login_form.cleaned_data['login']
            password = login_form.cleaned_data['password']

            # Uwierzytelnij użytkownika
            user = authenticate(request, username=login_value, password=password)
            if user is not None:
                # Logowanie powiodło się
                login(request, user)
                next_page = reverse('basic_app:map_page')
                return redirect(next_page)
            else:
                # Logowanie nie powiodło się
                # Dodaj odpowiedni komunikat błędu
                login_form.add_error(None, "Nieprawidłowy login lub hasło.")
    else:
        login_form = forms.LogIn()

    return render(request, 'basic_app/logowanie.html', {'login_form': login_form})

def about_page(request):
    user = request.user
    if user.is_authenticated:
        app_user = AppUsers.objects.get(user=user)
        avatar = str(app_user.avatar)
        context = {
            'user': user,
            'avatar': avatar,
        }
    else:
        context = {
            'user': user,
        }
    return render(request, 'basic_app/about.html', context)

@login_required(login_url='basic_app:login_page')
def dashboard_page(request):
    user = request.user
    if user.is_authenticated:
        app_user = AppUsers.objects.get(user=user)
        name = app_user.name
    return render(request, 'basic_app/dashboard.html', {'name':name})

@login_required(login_url='basic_app:login_page')
def map_page(request):
    current_time = timezone.now()
    two_minutes_ago = current_time - timezone.timedelta(minutes=120)
    Zgloszenie.objects.filter(czas_dodania__lte=two_minutes_ago).delete()
    print(two_minutes_ago, "     ", Zgloszenie)

    
    utrudnienia = Zgloszenie.objects.filter(typ_zgloszenia=1).values_list('x', 'y', 'czas_dodania', 'ID_Uzytkownika__login','typ_zgloszenia')
    utrudnienia = [(float(x), float(y), czas_dodania.strftime('%Y-%m-%dT%H:%M:%S'), login, typ) for x, y, czas_dodania, login, typ in utrudnienia]


    kontrole = Zgloszenie.objects.filter(typ_zgloszenia=2).values_list('x', 'y', 'czas_dodania', 'ID_Uzytkownika__login', 'typ_zgloszenia')
    kontrole = [(float(x), float(y), czas_dodania.strftime('%Y-%m-%dT%H:%M:%S'), login, typ) for x, y, czas_dodania, login, typ in kontrole]

    fotoradary = Zgloszenie.objects.filter(typ_zgloszenia=3).values_list('x', 'y', 'czas_dodania', 'ID_Uzytkownika__login', 'typ_zgloszenia')
    fotoradary = [(float(x), float(y), czas_dodania.strftime('%Y-%m-%dT%H:%M:%S'), login, typ) for x, y, czas_dodania, login, typ in fotoradary]
    
    user = request.user
    app_user = AppUsers.objects.get(user=user)
    avatar = str(app_user.avatar)

    form = forms.SearchCords()
    cordx = str(50.041088)
    cordy = str(21.999156)
    zoom = 13
    search_pin=False
    if(request.method =="POST"):
        form = forms.SearchCords(request.POST)
        if form.is_valid():
            search_pin = True
            adress = str(form.cleaned_data['adress']).split(",")
            if len(str(adress[0])) >1:
                try:
                    cords = get_coordinates(adress[0],adress[1])
                except IndexError:
                    cords = get_coordinates(adress[0],'')
                if cords == False:
                    messages.error(request, 'nie znaleziono adresu')
                    next_page = reverse('basic_app:map_page')
                    return redirect(next_page)
                else:   
                    cordx = cords[0]
                    cordy = cords[1]
                zoom = 16
                print(form.cleaned_data['adress'])
    context = {
            'form':form,
            'cordx':cordx,
            'cordy':cordy,
            'zoom':zoom,
            'search_pin':search_pin,
            'utrudnienia': utrudnienia,
            'fotoradary':fotoradary,
            'kontrole':kontrole,
            'avatar':avatar,
        }
    return render(request, 'basic_app/mapa.html', context)



@login_required(login_url='basic_app:login_page')
def settings_page(request):
    user = request.user
    if user.is_authenticated:
        app_user = AppUsers.objects.get(user=user)
        # Tutaj masz dostęp do pól modelu AppUsers dla zalogowanego użytkownika
        name = app_user.name
        last_name = app_user.last_name
        login = app_user.login
        email = app_user.email
        user_id = app_user.ID_Uzytkownika
        avatar = str(app_user.avatar)

        password = app_user.password[0]+ "****" + app_user.password[-1]

        context = {
            'name': name,
            'last_name': last_name,
            'login': login,
            'email': email,
            'id' : user_id,
            'password': password,
            'avatar':avatar,
        }
    return render(request, 'basic_app/ustawienia.html', context)

def sign_page(request):
    form = forms.NewAccount()
    if(request.method =="POST"):
        form = forms.NewAccount(request.POST)
        if form.is_valid():
            # przypisanie loginu i hasła do zmiennych
            login=form.cleaned_data['login']
            password=form.cleaned_data['password']
            # utworzenie modelu newUser
            newUser = AppUsers()
            # przypisanie danych do modelu
            newUser.name = form.cleaned_data['name']
            newUser.last_name=form.cleaned_data['last_name']
            newUser.email=form.cleaned_data['email']
            newUser.login = login
            newUser.password = password
            newUser.avatar = random.randint(1, 9)
            #przypisanie danych do autoryzacji podczas logowania
            user = User.objects.create_user(username=login, password=password)
            newUser.user = user
            # zapisanie danych w bazie
            newUser.save()
            user.save()
            return login_page(request)
        else:
            print("error form fdafas")
            
    return render(request, 'basic_app/rejestracja.html',{'form':form})


def logout_page(request):
    logout(request)
    next_page = reverse('basic_app:main_page')
    return redirect(next_page)

def send_trafic_data(request):
    if request.method == 'POST':
        user = request.user
        app_user = AppUsers.objects.get(user=user)
        report_trafic = Zgloszenie()
        data = json.loads(request.body)
        x = data.get('variable1')
        y = data.get('variable2')
        typ_zgloszenia = data.get('variable3')

        report_trafic.ID_Uzytkownika = app_user
        report_trafic.x = x
        report_trafic.y = y
        report_trafic.typ_zgloszenia = typ_zgloszenia
        report_trafic.save()
        print(x, "  " , y , "   " , typ_zgloszenia)

        # Wykonaj dalsze czynności z otrzymanymi danymi

        return JsonResponse({'message': 'Dane odebrane poprawnie.'})

    return JsonResponse({'message': 'Metoda nieobsługiwana.'}, status=405)


def map_the_route(request):
    if request.method == 'POST':
        # Odczytaj dane przesłane z frontendu
        adress1 = request.POST.get('variable1')
        adress2 = request.POST.get('variable2')

        # Wykonaj dowolne operacje na przesłanych danych
        adress1 = str(adress1).split(",")
        adress2 = str(adress2).split(",")
        if len(str(adress1[0])) >1:
            try:
                cords = get_coordinates(adress1[0],adress1[1])
            except IndexError:
                cords = get_coordinates(adress1[0],'')
            if cords == False:
                messages.error(request, 'nie znaleziono adresu')
                next_page = reverse('basic_app:map_page')
                return redirect(next_page)
            else:   
                x1 = cords[0]
                y1 = cords[1]
            print(adress1)

        if len(str(adress2[0])) >1:
            try:
                cords = get_coordinates(adress2[0],adress2[1])
            except IndexError:
                cords = get_coordinates(adress2[0],'')
            if cords == False:
                messages.error(request, 'nie znaleziono adresu')
                next_page = reverse('basic_app:map_page')
                return redirect(next_page)
            else:   
                x2 = cords[0]
                y2 = cords[1]
            print(adress2)

templates/basic_app/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-562KDCJ99B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-562KDCJ99B');
</script>
  <title>MapWay - Dashboard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="Ikony/Logo_14x14.png">
  <link rel="stylesheet" type="text/css" href="{% static 'style/style_log_rej.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static "style/style.css"%}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

  <!--menu-->

  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand justify-content-start"  href="{% url "basic_app:main_page" %}">
        <img src="{%static "Ikony/logotyp_v1.svg" %}" alt="Logo" width="300" height="80" class="d-inline-block align-text-top">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:map_page" %}">Mapa</a>
          </li>
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:about_page" %}">O nas</a>
          </li>
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:logout_page" %}">
              <img src="{% static 'Ikony/logout.svg' %}" alt="Logout" width="100" height="40" class="d-inline-block align-text-top"></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--sidebar-->

  <div class="sidebar bg-light">
    <a href="{% url 'basic_app:dashboard_page' %}" class="d-flex align-items-center  active">
      <img src="{% static 'Ikony/dashboard.svg' %}" alt="Dashboard" height="25" class="mr-2">
      <span class="sidebar-text">&emsp;Dashboard</span>
    </a>
    <a class="d-flex align-items-center" href="{% url 'basic_app:settings_page' %}">
      <img src="{% static 'Ikony/settings.svg' %}" alt="Ustawienia" height="25" class="">
      <span class="sidebar-text">&emsp;Ustawienia</span>
    </a>
  </div>

  <!--content-->
  <div class="content">
    <div class="container py-3">

      <header>
        <div class="dashboard" style="text-align: left;">
          <h1 class=" fw-normal">Dashboard</h1>
          <p class="fs-5">Witaj {{name}}!<br>
            Zróbmy coś razem</p>
        </div>
      </header>

      <main>
        <div class="row row-cols-1 row-cols-md-2 mb-2 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3" style="background-color: #2F52A0;color: #fff">
                <h4 class="my-0 fw-normal">Dzisiejszy wynik</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>10 users included</li>
                  <li>2 GB of storage</li>
                  <li>Email support</li>
                  <li>Help center access</li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3" style="background-color: #2F52A0;color: #fff">
                <h4 class="my-0 fw-normal">Historia</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>10 users included</li>
                  <li>2 GB of storage</li>
                  <li>Email support</li>
                  <li>Help center access</li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3" style="background-color: #2F52A0;color: #fff">
                <h4 class="my-0 fw-normal">Statystyki</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>10 users included</li>
                  <li>2 GB of storage</li>
                  <li>Email support</li>
                  <li>Help center access</li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3" style="background-color: #2F52A0;color: #fff">
                <h4 class="my-0 fw-normal">Ulubione</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>10 users included</li>
                  <li>2 GB of storage</li>
                  <li>Email support</li>
                  <li>Help center access</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</body>

</html>

templates/basic_app/ustawienia.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">

<head>
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-562KDCJ99B"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-562KDCJ99B');
</script>
  <title>MapWay - Dashboard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="Ikony/Logo_14x14.png">
  <link rel="stylesheet" type="text/css" href="{% static 'style/style_log_rej.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static "style/style.css"%}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

  <!--menu-->

  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand justify-content-start"  href="{% url "basic_app:main_page" %}">
        <img src="{%static "Ikony/logotyp_v1.svg" %}" alt="Logo" width="300" height="80" class="d-inline-block align-text-top">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:map_page" %}">Mapa</a>
          </li>
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:about_page" %}">O nas</a>
          </li>
          <li class="nav-item d-flex align-items-center justify-content-center">
            <a class="nav-link" href="{% url "basic_app:logout_page" %}">
              <img src="{% static 'Ikony/logout.svg' %}" alt="Logout" width="100" height="40" class="d-inline-block align-text-top"></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--sidebar-->

  <div class="sidebar bg-light">
    <!--<a href="{% url 'basic_app:dashboard_page' %}" class="d-flex align-items-center">
      <img src="{% static 'Ikony/dashboard.svg' %}" alt="Dashboard" height="25" class="mr-2">
      <span class="sidebar-text">&emsp;Dashboard</span>
    </a>-->
    <a class="d-flex align-items-center active" href="{% url 'basic_app:settings_page' %}">
      <img src="{% static 'Ikony/settings.svg' %}" alt="Ustawienia" height="25" class="">
      <span class="sidebar-text">&emsp;Ustawienia</span>
    </a>
  </div>
  

  <!--content-->
<div class="content">
  <div class="container">
    <div class="align-items-center rounded-3 border shadow-lg">
      <h1 class="my-0 fw-normal" style="color: #2F52A0;">Ustawienia</h1>
      <div class="col-lg-4 overflow-hidden shadow-lg" style="margin: auto; width: 380px;">
        {% with avatar=avatar %}
            <img src="{% static 'avatar/'|add:avatar|add:'.png' %}" alt="Avatar" width="300" height="300" class="d-inline-block lign-text-top" id="avatar_u">
        {% endwith %}
      </div>
      <!--<button class="submit" id="btn_3">Zmień awatar</button>-->
      <div class="row row-cols-1 row-cols-md-2 mb-2 text-center pt-lg-5" style="margin:auto; padding-right: 35px;">
        <div class="col" style="text-align: center;">
          <ul class="overall" style="margin:auto;">
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex; justify-content: space-between;">
                <span style="margin:auto;">Imie: {{name}}</span>
                <button class="btn btn-light btn-sm" onclick="change(1)">Zmień</button>
              </span>
            </li>
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex; justify-content: space-between;">
                <span style="margin:auto;">Login: {{login}}</span>
                <button class="btn btn-light btn-sm" onclick="change(2)">Zmień</button>
              </span>
            </li>
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex; justify-content: space-between;">
                <span style="margin:auto;">ID: {{id}}</span>
                <button class="btn btn-light btn-sm" style="display: none;">Zmień</button>
              </span>
            </li>
          </ul>
        </div>
        <div class="col" style="text-align: center;">
          <ul class="overall" style="margin:auto;">
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex;">
                <span style="margin:auto;">Nazwisko: {{last_name}}</span>
                <button class="btn btn-light btn-sm" onclick="change(3)">Zmień</button>
              </span>
            </li>
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex;">
                <span style="margin:auto;">Email: {{email}}</span>
                <button class="btn btn-light btn-sm" onclick="change(4)">Zmień</button>
              </span>
            </li>
            <li style="line-height: 2;">
              <span class="align-middle" style="display: flex; justify-content: space-between;">
                <span style="margin:auto;">Hasło: {{password}}</span>
                <button class="btn btn-light btn-sm" onclick="change(5)">Zmień</button>
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

  <script>
      
    function getCookie(name) {
      const cookieValue = document.cookie.match('(^|;)\\s*' + name + '\\s*=\\s*([^;]+)');
      return cookieValue ? cookieValue.pop() : '';
    }


    function getCookie(name) {
      const cookieValue = document.cookie.match('(^|;)\\s*' + name + '\\s*=\\s*([^;]+)');
      return cookieValue ? cookieValue.pop() : '';
    }
    
    function sendVariablesToDjango(var1, var2) {
      // Utwórz obiekt zawierający dane do wysłania
      const data = {
        variable1: var1,
        variable2: var2,
      };
    
      fetch('{% url "basic_app:change_user_data" %}', {
        method: 'POST',
        headers: {
          'X-CSRFToken': getCookie('csrftoken')  // Dodaj token CSRF do nagłówka żądania
        },
        body: JSON.stringify(data) // Dodaj konwersję obiektu na ciąg JSON
      })
        .then(response => {
          if (response.ok) {
            // Odpowiedź jest prawidłowa
            console.log('Dane zostały przesłane do Django.');
            // Przetwarzanie odpowiedzi
            return response.json();
          } else {
            // Odpowiedź jest błędna
            console.log('Wystąpił błąd podczas przesyłania danych do Django.');
            throw new Error('Błąd podczas przesyłania danych do Django.');
          }
        })
        .then(data => {
          console.log('Odpowiedź z Django:', data);
          // Tutaj możesz wykorzystać zwrócone wartości
          // np. przypisać do zmiennych, wyświetlić wyniki itp.
          alert(data.message)
        })
        .catch(error => {
          console.log('Wystąpił błąd:', error);
        });
    }
    
    function change(selected_field) {
      let promptText = '';
      switch (selected_field) {
        case 1:
          promptText = 'Podaj nowe imię:';
          break;
        case 2:
          promptText = 'Podaj nowy login:';
          break;
        case 3:
          promptText = 'Podaj nowe nazwisko:';
          break;
        case 4:
          promptText = 'Podaj nowy email:';
          break;
        case 5:
          promptText = 'Podaj nowe hasło:';
          break;
        default:
          promptText = 'Podaj dane:';
      }
      const result = prompt(promptText);
      if (result !== null) {
        // Użytkownik wprowadził dane
        sendVariablesToDjango(result, selected_field);
      }
    }
    

    
    




  </script>
  
  
</body>

</html>